name: customer_app
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  permission_handler: ^5.0.1+1
  injectable: ^1.0.4
  get_it: ^4.0.4
  get: ^3.17.1
  event_bus: ^1.1.1
  synchronized: ^2.2.0+2
  shared_preferences: ^0.5.12+4

  # UI
  google_fonts: ^1.1.1
  flutter_easyloading: ^2.0.1
  fluttertoast: ^7.1.1
  flutter_icons: ^1.1.0
  google_maps_flutter: ^1.0.6
  dots_indicator: ^1.2.0

  # Restful
  dio: ^3.0.7
  retrofit: ^1.0.1+1
  json_serializable: ^3.2.3
  json_annotation: ^3.0.0

  # FCM
  firebase_messaging: ^7.0.3
  flutter_local_notifications: ^3.0.0

  # Helpers
  logger: ^0.9.2
  intl: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  injectable_generator: ^1.0.4
  retrofit_generator: ^1.3.7+6
  flutter_gen: ^1.2.0

flutter_gen:
  output: lib/generated

flutter:
  uses-material-design: true
  assets:
    - resources/langs/
    - resources/images/